apiVersion: v1
kind: Service
metadata:
  name: dummy-restgateway
  labels:
    role: dummy-restgateway
spec:
  ports:
  - nodePort: 31080
    port: 8080
    protocol: TCP
    targetPort: 8080
    name: management-port
  type: NodePort
  selector:
    component: dummy-restgateway
